; -- Created with ISN Form Studio 2 for ISN AutoIt Studio -- ;
#include <StaticConstants.au3>
#include <GUIConstantsEx.au3>
#include <WindowsConstants.au3>
#Include <GuiButton.au3>
#include <GuiListView.au3>

$guiTest = GUICreate("Test Listview",520,423,-1,-1,-1,-1)
$text = "test1|test2|tes3" & @CRLF & "t1|t2|t3"
$lvTest = GUICtrlCreatelistview("c1|c2|c3",40,20,406,332,-1,$WS_EX_CLIENTEDGE)
Local $arr = [ ["test1", "test2", "test3"], ["b1", "b2", "b3"] ]
_GUICtrlListView_AddArray($lvTest, $arr)



#cs
[gui]
Handle_deklaration=default
Handle_deklaration_const=false
title=Test Listview
breite=520
hoehe=423
style=-1
exstyle=-1
bgcolour=0xF0F0F0
bgimage=none
handle=$guiTest
parent=
code=$text = "test1|test2|tes3" & @CRLF & "t1|t2|t3"[BREAK]
codebeforegui=
xpos=-1
ypos=-1
center_gui=true
title_textmode=normal
isf_include_once=false
only_controls_in_isf=false
const_modus=default
gui_code_in_function=false
gui_code_in_function_name=
gui_event_close=
gui_event_minimize=
gui_event_restore=
gui_event_maximize=
gui_event_mousemove=
gui_event_primarydown=
gui_event_primaryup=
gui_event_secoundarydown=
gui_event_secoundaryup=
gui_event_resized=
gui_event_dropped=
defaultfont=Tahoma
defaultfontsize=12
[0x00201814]
type=listview
handle=433
locked=0
resize=
x=40
y=20
width=406
height=332
func=
font=MS Sans Serif
fontsize=8
fontstyle=400
fontattribute=0
tooltip=
bgimage=
textcolour=0x000000
id=$lvTest
text=c1|c2|c3
state=$GUI_SHOW+$GUI_ENABLE
style=
exstyle=$WS_EX_CLIENTEDGE
bgcolour=
code=Local $arr = [ ["test1", "test2", "test3"], ["b1", "b2", "b3"] ][BREAK]_GUICtrlListView_AddArray($lvTest, $arr)
order=0
tabpage=-1
iconindex=
iconlarge=0
textmode=text
#ce
